#模块
filebeat.config.modules:
  path: ./modules.d/*.yml
  reload.enabled: true
setup.template.settings: 
  index.number_of_shards: 3
setup.kibana:
  host: "192.168.1.218:5601"
output.elasticsearch:
  hosts: ["192.168.1.217:9200","192.168.1.218:9200","192.168.1.219:9201"]
  username: "elastic"
  password: "ynjjkj"
